export const TOOL_REGISTRY = [
  {
    id: 'rad',
    name: 'Zufallsrad',
    icon: '🎡',
    color: '#BF00FF',
    description: 'Zufälliges Todo auswählen',
    standalone: true,
    integrated: false,
  },
  {
    id: 'timer',
    name: 'Fokus-Timer',
    icon: '⏱',
    color: '#00CFFF',
    description: 'Pomodoro & Fokus-Blöcke',
    standalone: true,
    integrated: false,
  },
  {
    id: 'rezepte',
    name: 'Rezepte',
    icon: '🍳',
    color: '#FF9F43',
    description: 'Rezepte, Einkauf, Vorräte',
    standalone: true,
    integrated: false,
  },
  {
    id: 'pizza',
    name: 'Pizza-Rechner',
    icon: '🍕',
    color: '#FF6B6B',
    description: 'Teig-Rechner & Zeitplan',
    standalone: true,
    integrated: false,
  },
  {
    id: 'elvi',
    name: 'Elvi',
    icon: '💊',
    color: '#00E5FF',
    description: 'Methylphenidat Dosisplanung',
    standalone: true,
    integrated: false,
  },
  {
    id: 'gewicht',
    name: 'Gewicht',
    icon: '⚖',
    color: '#00FF94',
    description: 'Gewichtstracking & Verlauf',
    standalone: true,
    integrated: true,
  },
  {
    id: 'geburtstage',
    name: 'Geburtstage',
    icon: '🎂',
    color: '#FF2D78',
    description: 'Geburtstage & Erinnerungen',
    standalone: true,
    integrated: true,
  },
  {
    id: 'gamification',
    name: 'XP & Level',
    icon: '⚡',
    color: '#FFD700',
    description: 'Punkte für Selbstregulation',
    standalone: false,
    integrated: true,
  },
]
