export const MODULE_CONFIG = {
  alertness: {
    id: 'alertness',
    name: 'Alertness',
    color: '#2DD4BF',
    domain: 'Reaktion',
    desc: 'Tippe so schnell wie möglich wenn der Kreis erscheint.',
    duration: 'ca. 2,5 Minuten',
    measured: ['Reaktionszeit (ms)', 'Fehler (Falschtippen)', 'Auslasser (verpasst)'],
    notMeasured: ['Intelligenz', 'Ablenkungen außerhalb des Screens'],
    mainMetricLabel: 'Ø Reaktionszeit',
    mainMetricUnit: 'ms',
    variants: ['Ohne Ton', 'Mit Warnton'],
    defaultVariant: 'Ohne Ton',
  },
  zahlensuche: {
    id: 'zahlensuche',
    name: 'Zahlensuche',
    color: '#38BDF8',
    domain: 'Tempo',
    desc: '25 Felder mit Zahlen 01–25. Tippe sie in Reihenfolge so schnell wie möglich.',
    duration: 'ca. 2–4 Minuten',
    measured: ['Gesamtzeit (s)', 'Fehler', 'Zeit pro Zahl'],
    notMeasured: ['Rechenkenntnisse', 'Ablenkungen außerhalb des Screens'],
    mainMetricLabel: 'Gesamtzeit',
    mainMetricUnit: 's',
    variants: ['Normal', 'Schwer', 'Rückwärts'],
    defaultVariant: 'Normal',
  },
  gedaechtnis: {
    id: 'gedaechtnis',
    name: 'Arbeitsgedächtnis',
    color: '#A78BFA',
    domain: 'Gedächtnis',
    desc: '12 Kreise leuchten nacheinander auf — merke dir die Sequenz.',
    duration: 'ca. 5 Minuten',
    measured: ['Korrekte Sequenzen', 'Fehler gesamt', 'Max. Sequenzlänge'],
    notMeasured: ['Gesamtintelligenz', 'Tagesform außerhalb der Übung'],
    mainMetricLabel: 'Korrekte Runden',
    mainMetricUnit: '',
    variants: ['Normal', 'Schwer'],
    defaultVariant: 'Normal',
  },
  gonogo: {
    id: 'gonogo',
    name: 'Go / No-Go',
    color: '#34D399',
    domain: 'Impulskontrolle',
    desc: 'Tippe bei Grün, halte still bei Rot.',
    duration: 'ca. 3 Minuten',
    measured: ['Reaktionszeit bei Go', 'Fehlerrate bei No-Go (Impulsivität)', 'Auslasser'],
    notMeasured: ['Konzentration auf äußere Reize', 'Emotionale Kontrolle'],
    mainMetricLabel: 'Ø Reaktionszeit',
    mainMetricUnit: 'ms',
    variants: ['Normal', 'Schwer'],
    defaultVariant: 'Normal',
  },
  nback: {
    id: 'nback',
    name: 'N-Back',
    color: '#818CF8',
    domain: 'Arbeitsgedächtnis',
    desc: 'Tippe wenn das aktuelle Symbol dasselbe ist wie das vorherige.',
    duration: 'ca. 4 Minuten',
    measured: ['Treffer', 'Fehler', 'Auslasser'],
    notMeasured: ['Reaktionsgeschwindigkeit', 'Sprachkenntnisse'],
    mainMetricLabel: 'Treffer-Rate',
    mainMetricUnit: '%',
    variants: ['Normal', 'Schwer'],
    defaultVariant: 'Normal',
  },
  taskswitching: {
    id: 'taskswitching',
    name: 'Task Switching',
    color: '#FBBF24',
    domain: 'Flexibilität',
    desc: 'Die Regel wechselt — einmal Form, einmal Farbe matchen.',
    duration: 'ca. 4 Minuten',
    measured: ['Reaktionszeit', 'Switch Cost (RT-Einbruch nach Regelwechsel)', 'Fehler nach Wechsel'],
    notMeasured: ['Allgemeine Intelligenz', 'Kreativität'],
    mainMetricLabel: 'Switch Cost',
    mainMetricUnit: 'ms',
    variants: ['Normal', 'Schwer'],
    defaultVariant: 'Normal',
  },
  geteilt: {
    id: 'geteilt',
    name: 'Geteilte Aufmerksamkeit',
    color: '#22D3EE',
    domain: 'Multitasking',
    desc: 'Bild und Ton gleichzeitig im Blick behalten — tippe sobald eines der Signale auftritt.',
    steps: [
      'Jede Runde: 5 Kreise erscheinen, dazu ein Ton (HOCH oder TIEF).',
      'Tippe wenn genau ein Kreis ausgefüllt ist (nicht bei keinem, nicht bei mehreren).',
      'Tippe auch wenn der Ton derselbe ist wie im vorherigen Beat (Wiederholung).',
      'Treffen beide gleichzeitig zu — einmal tippen genügt.',
      'Kein Signal → nicht tippen.',
    ],
    duration: 'ca. 3 Minuten',
    measured: ['Treffer visuell', 'Treffer auditiv', 'Fehler gesamt'],
    notMeasured: ['Reaktionszeit', 'Hörfähigkeit'],
    mainMetricLabel: 'Gesamt-Treffer',
    mainMetricUnit: '%',
    variants: ['Normal', 'Schwer'],
    defaultVariant: 'Normal',
  },
}

export const MODULE_ORDER = [
  'alertness', 'zahlensuche', 'gedaechtnis',
  'gonogo', 'nback', 'taskswitching', 'geteilt',
]
export const PHASE2_MODULES = []
