export const MODULE_CONFIG = {
  alertness: {
    id: 'alertness',
    name: 'Alertness',
    color: '#2DD4BF',
    domain: 'Reaktion',
    desc: 'Tippe so schnell wie möglich wenn der Kreis erscheint.',
    duration: 'ca. 2,5 Minuten',
    measured: ['Reaktionszeit (ms)', 'Fehler (Falschtippen)', 'Auslasser (verpasst)'],
    notMeasured: ['Intelligenz', 'Ablenkungen außerhalb des Screens'],
    mainMetricLabel: 'Ø Reaktionszeit',
    mainMetricUnit: 'ms',
    higherIsBetter: false,
  },
  zahlensuche: {
    id: 'zahlensuche',
    name: 'Zahlensuche',
    color: '#38BDF8',
    domain: 'Visuelle Suche',
    desc: '25 Felder mit Zahlen 01–25. Tippe sie in Reihenfolge so schnell wie möglich.',
    duration: 'ca. 2–4 Minuten',
    measured: ['Gesamtzeit (s)', 'Fehler', 'Zeit pro Zahl'],
    notMeasured: ['Rechenkenntnisse', 'Ablenkungen außerhalb des Screens'],
    mainMetricLabel: 'Gesamtzeit',
    mainMetricUnit: 's',
    higherIsBetter: false,
  },
  gedaechtnis: {
    id: 'gedaechtnis',
    name: 'Merkspanne',
    color: '#A78BFA',
    domain: 'Gedächtnis',
    desc: 'Kreise leuchten nacheinander auf — merke dir die Sequenz. Sie wird jede Runde länger.',
    duration: 'läuft bis 2 Fehler',
    measured: ['Max. Sequenzlänge', 'Geschaffte Runden', 'Fehler gesamt'],
    notMeasured: ['Gesamtintelligenz', 'Tagesform außerhalb der Übung'],
    mainMetricLabel: 'Max. Sequenzlänge',
    mainMetricUnit: '',
    higherIsBetter: true,
  },
  gonogo: {
    id: 'gonogo',
    name: 'Go / No-Go',
    color: '#34D399',
    domain: 'Impulskontrolle',
    desc: 'Tippe bei Grün, halte still bei Rot.',
    duration: 'ca. 3 Minuten',
    measured: ['Reaktionszeit bei Go', 'Fehlerrate bei No-Go (Impulsivität)', 'Auslasser'],
    notMeasured: ['Konzentration auf äußere Reize', 'Emotionale Kontrolle'],
    mainMetricLabel: 'Ø Reaktionszeit',
    mainMetricUnit: 'ms',
    higherIsBetter: false,
  },
  nback: {
    id: 'nback',
    name: 'N-Back',
    color: '#818CF8',
    domain: 'Arbeitsgedächtnis',
    desc: 'Tippe wenn das Symbol mit dem vorherigen übereinstimmt.',
    duration: 'ca. 4 Minuten',
    measured: ['Treffer', 'Fehler', 'Auslasser'],
    notMeasured: ['Reaktionsgeschwindigkeit', 'Sprachkenntnisse'],
    mainMetricLabel: 'Treffer-Rate',
    mainMetricUnit: '%',
    higherIsBetter: true,
  },
  taskswitching: {
    id: 'taskswitching',
    name: 'Task Switching',
    color: '#FBBF24',
    domain: 'Flexibilität',
    desc: 'Die Regel wechselt — einmal Form, einmal Farbe matchen.',
    duration: 'ca. 4 Minuten',
    measured: ['Reaktionszeit', 'Switch Cost (RT-Einbruch nach Regelwechsel)', 'Fehler nach Wechsel'],
    notMeasured: ['Allgemeine Intelligenz', 'Kreativität'],
    mainMetricLabel: 'Switch Cost',
    mainMetricUnit: 'ms',
    higherIsBetter: false,
  },
  stroop: {
    id: 'stroop',
    name: 'Stroop',
    color: '#F472B6',
    domain: 'Selektive Aufmerksamkeit',
    desc: 'Tippe die FARBE, in der das Wort geschrieben ist — nicht das Wort selbst.',
    duration: 'ca. 2,5 Minuten',
    measured: ['Trefferquote', 'Ø Reaktionszeit', 'Interferenz (inkongruent − kongruent)'],
    notMeasured: ['Lesegeschwindigkeit', 'Farbsehschwäche'],
    mainMetricLabel: 'Trefferquote',
    mainMetricUnit: '%',
    higherIsBetter: true,
  },
  speedsort: {
    id: 'speedsort',
    name: 'Speed-Sort',
    color: '#22D3EE',
    domain: 'Tempo & Dauerfokus',
    desc: 'Stimmt das Symbol mit dem Ziel oben überein? ✓ wenn ja, ✗ wenn nein — so schnell wie möglich.',
    duration: '90 Sekunden',
    measured: ['Richtige pro Minute', 'Genauigkeit', 'Ø Entscheidungszeit'],
    notMeasured: ['Gedächtnis', 'Reaktion auf Einzelreize'],
    mainMetricLabel: 'Richtige/min',
    mainMetricUnit: '/min',
    higherIsBetter: true,
  },
  // Archiviert: aus dem aktiven Roster entfernt (zu komplex), aber Config bleibt,
  // damit historische Sessions in Auswertung/Historie korrekt rendern. Nicht startbar.
  geteilt: {
    id: 'geteilt',
    name: 'Geteilte Aufmerksamkeit',
    color: '#22D3EE',
    domain: 'Multitasking',
    archived: true,
    desc: 'Bild und Ton gleichzeitig im Blick behalten — tippe sobald eines der Signale auftritt.',
    steps: [
      'Jede Runde: 5 Kreise erscheinen, dazu ein Ton (HOCH oder TIEF).',
      'Tippe wenn genau ein Kreis ausgefüllt ist (nicht bei keinem, nicht bei mehreren).',
      'Tippe auch wenn der Ton derselbe ist wie im vorherigen Beat (Wiederholung).',
      'Treffen beide gleichzeitig zu — einmal tippen genügt.',
      'Kein Signal → nicht tippen.',
    ],
    duration: 'ca. 3 Minuten',
    measured: ['Treffer visuell', 'Treffer auditiv', 'Fehler gesamt'],
    notMeasured: ['Reaktionszeit', 'Hörfähigkeit'],
    mainMetricLabel: 'Gesamt-Treffer',
    mainMetricUnit: '%',
    higherIsBetter: true,
  },
}

export const MODULE_ORDER = [
  'alertness', 'zahlensuche', 'gedaechtnis', 'gonogo',
  'nback', 'taskswitching', 'stroop', 'speedsort',
]

// Profil-Domänen für die „Form pro Domäne"-Ansicht — gruppiert die Module.
export const PROFILE_DOMAINS = {
  aufmerksamkeit:  { label: 'Aufmerksamkeit',  color: '#2DD4BF', modules: ['alertness', 'stroop'] },
  gedaechtnis:     { label: 'Gedächtnis',      color: '#A78BFA', modules: ['gedaechtnis', 'nback'] },
  tempo:           { label: 'Tempo',           color: '#38BDF8', modules: ['zahlensuche', 'speedsort'] },
  impulskontrolle: { label: 'Impulskontrolle', color: '#34D399', modules: ['gonogo'] },
  flexibilitaet:   { label: 'Flexibilität',    color: '#FBBF24', modules: ['taskswitching'] },
}

export const PROFILE_DOMAIN_ORDER = ['aufmerksamkeit', 'gedaechtnis', 'tempo', 'impulskontrolle', 'flexibilitaet']
